// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG0Q2tYSSHtIZltDlOK3aS_5dVXsKRgMQ',
    appId: '1:777666782319:web:d07a7afe83d7319f75599a',
    messagingSenderId: '777666782319',
    projectId: 'solace-vitaro',
    authDomain: 'solace-vitaro.firebaseapp.com',
    storageBucket: 'solace-vitaro.appspot.com',
    measurementId: 'G-3B1FBDZCR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNf_if4Jh3-H_Y9qVIEHptTZcfHohU9Us',
    appId: '1:777666782319:android:b1767b14f0fc6d1275599a',
    messagingSenderId: '777666782319',
    projectId: 'solace-vitaro',
    storageBucket: 'solace-vitaro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNlMVxZrL_EUvVi5evTBtIjswPozLowD4',
    appId: '1:777666782319:ios:55581ce6fd83316675599a',
    messagingSenderId: '777666782319',
    projectId: 'solace-vitaro',
    storageBucket: 'solace-vitaro.appspot.com',
    iosBundleId: 'com.example.solace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNlMVxZrL_EUvVi5evTBtIjswPozLowD4',
    appId: '1:777666782319:ios:55581ce6fd83316675599a',
    messagingSenderId: '777666782319',
    projectId: 'solace-vitaro',
    storageBucket: 'solace-vitaro.appspot.com',
    iosBundleId: 'com.example.solace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAG0Q2tYSSHtIZltDlOK3aS_5dVXsKRgMQ',
    appId: '1:777666782319:web:a30083895c9d7b6875599a',
    messagingSenderId: '777666782319',
    projectId: 'solace-vitaro',
    authDomain: 'solace-vitaro.firebaseapp.com',
    storageBucket: 'solace-vitaro.appspot.com',
    measurementId: 'G-BGJ3WTNXY7',
  );
}
