name: solace
description: "A Symptom Monitoring and Intervention App for Palliative and Hospice Care"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2 
  file_picker: ^8.1.3
  permission_handler: ^10.0.0
  url_launcher: ^6.0.0
  accordion: ^2.6.0
  table_calendar: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/auth/
    - lib/assets/images/caregiver/
    - lib/assets/images/user/
    - lib/assets/images/shared/
    - lib/assets/images/shared/header/
    - lib/assets/images/shared/info/
    - lib/assets/images/shared/functions/
    - lib/assets/images/shared/navigation/
    - lib/assets/images/shared/profile/
    - lib/assets/images/shared/vitals/
  fonts:
    - family: Inter
      fonts:
        - asset: lib/assets/fonts/Inter/Inter-Bold.ttf
        - asset: lib/assets/fonts/Inter/Inter-Regular.ttf
    - family: Outfit
      fonts:
        - asset: lib/assets/fonts/Outfit/Outfit-Bold.ttf
        - asset: lib/assets/fonts/Outfit/Outfit-Regular.ttf
