name: solace
description: "A Symptom Monitoring and Intervention App for Palliative and Hospice Care"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.4.4
  csv: ^6.0.0
  cupertino_icons: ^1.0.8
  file_picker: ^9.0.0
  firebase_app_check: ^0.3.1+6
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.4
  firebase_storage: ^12.3.6
  flutter:
    sdk: flutter
  flutter_email_sender: ^7.0.0
  flutter_form_builder: ^10.0.0
  flutter_local_notifications: ^18.0.1
  fluttertoast: ^8.2.12
  form_builder_validators: ^11.1.2
  google_sign_in: ^6.2.1
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  http: ^1.3.0
  intl: ^0.19.0
  local_auth: ^2.3.0
  path_provider: ^2.0.10
  pdf: ^3.6.0
  permission_handler: ^11.3.1
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  table_calendar: ^3.0.0
  timezone: ^0.10.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "lib/assets/images/auth/app_icon.png"
  name: "Solace"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/solace-28954-firebase-adminsdk-xa5bk-d441055ef8.json
    - lib/assets/
    - lib/assets/images/auth/
    - lib/assets/images/caregiver/
    - lib/assets/images/admin/
    - lib/assets/images/predefined/
    - lib/assets/images/predefined/caregiver/
    - lib/assets/images/predefined/doctor/
    - lib/assets/images/predefined/nurse/
    - lib/assets/images/predefined/patient/
    - lib/assets/images/shared/
    - lib/assets/images/shared/navigation/
    - lib/assets/images/shared/profile/
    - lib/assets/images/shared/vitals/
  fonts:
    - family: Inter
      fonts:
        - asset: lib/assets/fonts/Inter/Inter-Bold.ttf
        - asset: lib/assets/fonts/Inter/Inter-Regular.ttf
    - family: Outfit
      fonts:
        - asset: lib/assets/fonts/Outfit/Outfit-Bold.ttf
        - asset: lib/assets/fonts/Outfit/Outfit-Regular.ttf
